

export const options = [
  { name: 'Limón' },
  { name: 'Ananá' },
  { name: 'Frutilla' },
  { name: 'Naranja' },
  { name: 'Durazno' },
  { name: 'Cereza' },
  { name: 'Coco' },
  { name: 'Banana' },
  { name: 'Banana Split' },
  { name: 'Vainilla' },
  { name: 'Granizado' },
  { name: 'Tramontana' },
  { name: 'Almendrado' },
  { name: 'Crema rusa' },
  { name: 'Crema americana' },
  { name: 'Crema americana sin azúcar' },
  { name: 'Dulce de leche' },
  { name: 'Dulce de leche granizado' },
  { name: 'Dulce de leche Tentación' },
  { name: 'Flan con dulce de leche' },
  { name: 'Chocolate' },
  { name: 'Chocolate blanco' },
  { name: 'Chocolate nevado' },
  { name: 'Chocolate relleno' },
  { name: 'Chocolate bariloche' },
  { name: 'Chocolate al rhum' },
  { name: 'Chocolate con almendras' },
  { name: 'Mousse de chocolate' },
  { name: 'Chocolate sin azúcar' },
  { name: 'Kinotos al whisky' },
  { name: 'Frutos del bosque' },
  { name: 'Frutilla a la crema' },
  { name: 'Mousse de Limón' },
  { name: 'Multifruta' },
  { name: 'Menta granizada' },
  { name: 'Maracuyá' },
  { name: 'Mascarpone' },
  { name: 'Sambayón' },
  { name: 'Sambayón relleno' },
  { name: 'Tiramisú' },
];
